{% set name = "graphium" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphium-{{ version }}.tar.gz
  sha256: 5805485ad38a7f95f55037b9fd5b4e47510f4c268dbf3a57236739e2c9acf1ba

build:
  entry_points:
    - graphium = graphium.cli:main_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - click
    - loguru
    - omegaconf >=2.0.0
    - tqdm
    - numpy
    - scipy >=1.4
    - pandas >=1.0
    - scikit-learn
    - fastparquet
    - matplotlib-base >=3.0.1
    - seaborn
    - fsspec >=2021.6
    - s3fs >=2021.6
    - gcsfs >=2021.6
    - platformdirs
    - pytorch >=1.10.2,<2.0
    - torchvision
    - pytorch-lightning >=1.9
    - torchmetrics >=0.7.0,<0.11
    - ogb
    - pytorch_geometric >=2.0
    - wandb
    - mup
    - pytorch_sparse >=0.6
    - pytorch_cluster >=1.5
    - pytorch_scatter >=2.0
    - datamol >=0.10
    - mordred

test:
  imports:
    - graphium
  commands:
    - graphium --help
    - graphium --version | grep {{ version }}

about:
  summary: 'Graphium: Scaling molecular GNNs to infinity.'
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/datamol-io/graphium

extra:
  recipe-maintainers:
    - hadim
    - DomInvivo
