{% set name = "graphium" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/datamol-io/graphium.git # Change to archive url - https://conda-forge.org/docs/maintainer/adding_pkgs/#build-from-tarballs-not-repos, url: https://github.com/datamol-io/graphium/archive/{{ version }}.tar.gz
  # sha256: compute checksum for tarball
  git_rev: "6bfbcb7"  # use a tag (be mindful of depth)
  #git_depth: 1

build:
  number: 0
  script: |
    export CXXFLAGS="${CXXFLAGS} -DNDEBUG"
    {{ PYTHON }} -m pip install . -vv --no-deps
  skip: true  # [py<39 or py>311]
  entry_points:
    - graphium = graphium.cli.main:app
    - graphium-train = graphium.cli.train_finetune_test:cli

requirements:
  build:
    - python
    - pybind11
    - {{ compiler('cxx') }}

  host:
    - python
    - pip
    - pybind11
    - pytorch <2.5
    - librdkit-dev
    - rdkit ==2024.03.4
    - boost
    - numpy ==1.25.0

  run:
    - python
    - typer
    - loguru
    - omegaconf >=2.0.0
    - tqdm
    - platformdirs
    - hydra-core

    # scientific
    - numpy ==1.25.0
    - scipy >=1.4
    - pandas >=1.0
    - scikit-learn
    - fastparquet

    # viz
    - matplotlib >=3.0.1
    - seaborn

    # cloud IO
    - fsspec >=2021.6
    - s3fs >=2021.6
    - gcsfs >=2021.6

    # ML packages
    - cuda-version
    - pytorch <2.5
    - lightning >=2.0
    - torchmetrics
    - ogb
    - pytorch_geometric >=2.0 
    - wandb >=0.18.5
    - mup
    - pytorch_sparse >=0.6
    - pytorch_cluster >=1.6
    - pytorch_scatter >=2.0

    # chemistry
    - rdkit ==2024.03.4
    - datamol >=0.10

test:
  requires:
    - pydantic <2
    - pytest >=6.0
    - pytest-xdist
    - pytest-cov
    - pytest-forked
    - nbconvert
    - black >=23
    - jupyterlab
    - ipywidgets
  imports:
    - graphium
  commands:
    - graphium --help
    - python -c "import graphium; assert graphium.__version__ == '{{ version }}'"

about:
  summary: 'Graphium: Scaling molecular GNNs to infinity.'
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/datamol-io/graphium

extra:
  recipe-maintainers:
    - Andrewq11
    - DomInvivo
