{% set name = "graphium" %}
{% set version = "2.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graphium-{{ version }}.tar.gz
  sha256: afa9bc39520e0fea2efa2cfcd555860a119cd2fbc8569fd422b8951dc43ecaa2

build:
  entry_points:
    - graphium = graphium.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - hydra-core
    - typer
    - loguru
    - omegaconf >=2.0.0
    - tqdm
    - platformdirs

    # scientific
    - numpy ==1.26.4
    - scipy >=1.4
    - pandas >=1.0
    - scikit-learn
    - fastparquet

    # viz
    - matplotlib-base >=3.0.1
    - seaborn

    # cloud IO
    - fsspec >=2021.6
    - s3fs >=2021.6
    - gcsfs >=2021.6

    # ML packages
    - pytorch >=1.12
    - lightning >=2.0
    - torchmetrics >=0.7.0,<0.11
    - ogb
    - pytorch_geometric >=2.0
    - wandb
    - mup
    - pytorch_sparse >=0.6
    - pytorch_cluster >=1.5
    - pytorch_scatter >=2.0

    # chemistry
    - rdkit
    - datamol >=0.10

test:
  requires:
    - pydantic <2
  imports:
    - graphium
  commands:
    - graphium --help

about:
  summary: 'Graphium: Scaling molecular GNNs to infinity.'
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/datamol-io/graphium

extra:
  recipe-maintainers:
    - Andrewq11
    - DomInvivo
